### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by siordon** [erikp9000/necclock#1]
@erikp9000 Trying to compile and TASM appeared to work but resulting file produces garble after the normal output, and always tries to set RTC from DOS once NECCLOCK.BIN is created. Can you please add a compiled version?

**Comment by erikp9000** [comment]
Thanks for the report! The source is written to be assembled with the Microsoft Assembler (MASM) and linked with the Microsoft Linker (LINK). There is also a defect in the program where it does not implement the '/s' switch. Instead, the presence of any character following the executable name, including a SPACE character, will cause the program to perform the 'Read DOS time and set RTC' function. I am uploading the executable now, but it still has the defect.

**Comment by siordon** [comment]
Great, thanks!

**Comment by siordon** [comment]
Garble must be related to the chip - I was hoping this might work with my card that has a UPD4990 but unfortunately it doesn't.

**Comment by erikp9000** [comment]
Is your card from Turner Hall Publishing? If not, then the address and port decoding might be completely different. If it is, the 4990 should be backwards compatible with the 1990, so if it's not working they must have changed the address and port decoding when they upgraded to the 4990. In either case, one might have to reverse-engineer the card's address and port decoding logic to determine if it's at the same port and implements the same registers...

**Comment by siordon** [comment]
Actually no it's a CTE Research CTE410B... can't find a utility that works with it, so I thought it was worth a shot. Can you give me any pointers on the reverse engineering process? (Can I email you?)

**Comment by erikp9000** [comment]
Sure.

Erik

**Comment by erikp9000** [comment]
Sure. ***@***.***

**Comment by siordon** [comment]
Thanks... but github censored it. Can you please make your address public, or see my profile for mine? Cheers :-)
